name: AdvancedServerManager
version: '${version}'
main: me.pavelsgarklavs.advancedservermanager.AdvancedServerManager
api-version: 1.17
authors: [ Dev_Fox ]
description: Use Advanced Server Manager to eliminate frustration and control your server with ease
website: pavelsgarklavs.me
commands:
  admin:
    description: Open a Admin GUI
    usage: /<command>
  gm:
    description: Change gamemode to Creative
    usage: /<command>
    aliases:
      - gamemode
