name: AdvancedServerManager
version: '${version}'
main: me.pavelsgarklavs.advancedservermanager.AdvancedServerManager
api-version: 1.17
authors: [ Dev_Fox ]
description: Use Advanced Server Manager to eliminate frustration and control your server with ease
website: pavelsgarklavs.me
commands:
  admin:
    description: Open a Admin GUI
    usage: /<command>
  gm:
    description: Change gamemode to yourself or the player
    usage: /<command> [gamemode, 0-3] [player]
    aliases:
      - gamemode
  fly:
    description: Turn on or off Fly for yourself or the player
    usage: /<command> [player]
  god:
    description: Turn on or off God Mode for yourself or the player
    usage: /<command> [player]
    aliases:
      - godmode
  feed:
    description: Feed yourself or the player
    usage: /<command> [player]
  heal:
    description: Heal youself or the player
    usage: /<command> [player]
  weather:
    description: Change weather
    usage: /<command> [clear, rain]
  time:
    description: Chane time
    usage: /<command> [day, night, number]