name: AdvancedServerManager
version: '${version}'
main: me.pavelsgarklavs.advancedservermanager.AdvancedServerManager
api-version: 1.18
authors: [ Dev_Pavels ]
description: Use Advanced Server Manager to eliminate frustration and control your server with ease
website: pavelsgarklavs.me
commands:
  admin:
    description: Open a Admin GUI
    usage: /<command>
  gm:
    description: Change gamemode to yourself or the player
    usage: /<command> [gamemode, 0-3] [player]
    aliases:
      - gamemode
  fly:
    description: Turn on or off Fly for yourself or the player
    usage: /<command> [player]
  god:
    description: Turn on or off God Mode for yourself or the player
    usage: /<command> [player]
    aliases:
      - godmode
  feed:
    description: Feed yourself or the player
    usage: /<command> [player]
  heal:
    description: Heal youself or the player
    usage: /<command> [player]
  weather:
    description: Change weather
    usage: /<command> [clear, rain]
  time:
    description: Change time
    usage: /<command> [day, night, number]
  home:
    description: Set home
    usage: /<command>
  sethome:
    description: Go home
    usage: /<command>
  tp:
    description: Teleport to player or player to you
    usage: /<command> [player] [Optional - to who teleport]
    aliases:
      - teleport
      - tel
  bm:
    description: Turn Build Mode on or off
    usage: /<command>
    aliases:
      - buildmode
  vanish:
    description: Hide from other players
    usage: /<command>
  setspawn:
    description: Set spawn for the Server
    usage: /<command>
  spawn:
    description: Go to spawn of the Server
    usage: /<command>